## 2.2.1 An exampl

In [1]:
#add library
import numpy as np

In [2]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
a = a.reshape(3,5)

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6,7,8])

In [12]:
type(b)

numpy.ndarray

## 2.2.2 Array Creation

In [13]:
a = np.array([2,3,4])

In [14]:
a

array([2, 3, 4])

In [15]:
b = np.array([1.2,3.5,5.1])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones( (2,3,4),dtype=np.int16 ) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.empty( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [20]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.arange(0,2,0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements
obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace
that receives as an argument the number of elements that we want, instead of the step:

In [22]:
from numpy import pi

In [23]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
x = np.linspace(0,2*pi,100)

In [25]:
f = np.sin(x)

## 2.2.3 Printing Arrays


In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [29]:
print( np.arange(10000) )

[   0    1    2 ... 9997 9998 9999]


In [30]:
print( np.arange(10000).reshape(100,100) )

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using
set_printoptions.

## 2.2.4 Basic Operations

In [33]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [34]:
c = a + b
c

array([20, 31, 42, 53])

In [35]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [36]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a<35

array([ True,  True, False, False])

In [38]:
a[a<35]

array([20, 30])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product
can be performed using the @ operator (in python >=3.5) or the dot function or method:


In [39]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

a*b

array([[2, 0],
       [0, 4]])

In [40]:
a@b

array([[5, 4],
       [3, 4]])

In [41]:
a.dot(b)

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one

In [42]:
a = np.ones((2,3),dtype=int)
b = np.random.random((2,3))

a *= a
a

array([[1, 1, 1],
       [1, 1, 1]])

In [43]:
b += a
b

array([[1.03616711, 1.48200643, 1.33492415],
       [1.73135803, 1.85251472, 1.2538597 ]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise
one (a behavior known as upcasting).

In [44]:
a = np.ones(3,dtype=np.int32)
b = np.linspace(0,pi,3)

In [45]:
b.dtype.name

'float64'

In [46]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [47]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [48]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of
the ndarray class.


In [50]:
a = np.random.random((2,3))
a

array([[0.25892222, 0.64617355, 0.04823914],
       [0.42855375, 0.41056452, 0.3679271 ]])

In [51]:
a.sum()

2.1603802767367553

In [52]:
a.min()

0.0482391404391751

In [53]:
a.max()

0.6461735515392723

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However,
by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [54]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [56]:
b.min(axis=1)

array([0, 4, 8])

In [57]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)